### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by BohdanDymydiuk**
[DEMO LINK](https://BohdanDymydiuk.github.io/layout_KateVR/)
Some things I didn't make. Because of JS. For example slider.

### CODE REVIEW

**Review by vadiimvooo — CHANGES_REQUESTED** [review]
Good job. You should fix the button appearance.
1. This button hides the contact link on mobile screens:
image

**Comment by BohdanDymydiuk** [comment]
I did't hide button on mobile screens because I don't use JS now .

**Review by loralevitska — CHANGES_REQUESTED** [review]
You don't need JS for this (use media query and `display: none` property)
image
Please fix mobile mode according mockup 
image

If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review

**Comment by BohdanDymydiuk** [comment]
No, that's not what I was talking about. 
I asked mentors, they told me that should be a fixed button on mobile screens. When I talked about JS, I meant that when I sroll to the end of the page the "shadow-button" should be hidden. But I can't do it without JS. Because I need to learn Javascript Advanced.

**Review by vadiimvooo — APPROVED** [review]
Good job. You can try by your own to implement the scroll feature. Here is the [link](https://stackoverflow.com/questions/21032676/dynamically-show-hide-back-to-top-button-with-javascript) where described how you can do it.

**Pull request closed without merging**
